#!/sbin/runscript
# Copyright 1999-2013 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

AGENTPATH="/usr/local/nexyagent/agent.py"
PIDFILE="/var/run/nexyagent.pid"

[ -f $AGENTPATH ] || echo "/usr/local/nexyagent/agent.py not found"

depend() {
	need net
}

start() {
	ebegin "Starting daemon Nexyagent"
	start-stop-daemon --start --exec /usr/bin/python2.7 \
		-- ${AGENTPATH} start init --clean
	eend $?
}

stop() {
	ebegin "Stopping daemon Nexyagent"
	start-stop-daemon --start --exec /usr/bin/python2.7 \
		-- ${AGENTPATH} stop init
	eend $?

}
